const assert=require('node:assert/strict');
const fs=require('node:fs');
const X=require('../vendor/xlsx.full.min.js');
const D=require('../data.js');
const C=require('../calculator.js');
const workbook=X.read(fs.readFileSync(process.argv[2]),{type:'buffer',cellNF:true,cellText:true});
const sheet=D.cropSheet(workbook.Sheets['New Data']);
assert.deepEqual(D.detectLayout(sheet),{start:7,depth:2});
assert(!Object.keys(sheet).some(k=>/^(V|W|X|Y|Z|[A-Z]{2,})\d+$/.test(k)));
const table=D.parseSheet(sheet,7,2,X);
assert.equal(table.headers.length,21);
assert.equal(table.headers[2],'Temp-1');
assert.equal(table.headers[14],'T2-T1');
assert.equal(table.rows[0].sourceRow,9);
const pasted=X.utils.sheet_to_json(sheet,{header:1,range:'A7:L161',raw:true,defval:''});
const source=C.parseMatrix(pasted);
assert.equal(source.rows.length,149);assert.equal(source.summaryCount,1);
const pairs=C.makePairs(source.sensors,'example');
assert.deepEqual(pairs,[{a:2,b:1},{a:2,b:3},{a:5,b:4},{a:5,b:6},{a:8,b:7},{a:8,b:9}]);
const result=C.calculate(source,pairs);
assert.deepEqual(result.rows[0].slice(2),[0.75,0.10,0.93,-0.38,0.85,-0.95]);
let compared=0;
result.rows.forEach((r,i)=>r.slice(2).forEach((value,j)=>{
  const original=sheet[X.utils.encode_cell({r:i+8,c:j+14})];
  if(original?.t==='n'&&value!==null){assert(Math.abs(value-original.v)<0.011,`Difference mismatch at reading ${i+1}, pair ${j+1}: ${value} vs ${original.v}`);compared++;}
}));
assert(compared>600);
const clipboardSource=C.parseMatrix(X.utils.sheet_to_json(sheet,{header:1,range:'A7:L161',raw:false,defval:''}));
assert.deepEqual(C.calculate(clipboardSource,pairs).rows[0].slice(2),[0.7,0.1,0.9,-0.4,0.8,-1]);
// Headerless pastes must retain the first reading and the original differences.
const withoutHeaders=X.utils.sheet_to_json(sheet,{header:1,range:'A9:L161',raw:false,defval:''});
const inferred=C.parseMatrix(withoutHeaders);
assert.equal(inferred.inferred.layout,'date-hours');
assert.equal(inferred.rows.length,149);assert.equal(inferred.summaryCount,1);
assert.equal(inferred.sensors[9].ambient,true);
assert.deepEqual(C.calculate(inferred,pairs).rows,C.calculate(clipboardSource,pairs).rows);
const rawHeaderless=C.parseMatrix(X.utils.sheet_to_json(sheet,{header:1,range:'A9:L157',raw:true,defval:''}));
assert.equal(rawHeaderless.inferred.layout,'date-hours');
assert.deepEqual(C.calculate(rawHeaderless,pairs).rows,result.rows);
const temperatures=C.parseMatrix(withoutHeaders.slice(0,149).map(r=>r.slice(2)));
assert.equal(temperatures.inferred.layout,'temperatures');
assert.deepEqual(C.calculate(temperatures,pairs).rows.map(r=>r.slice(2)),C.calculate(clipboardSource,pairs).rows.map(r=>r.slice(2)));
const hoursOnly=C.parseMatrix(withoutHeaders.slice(0,149).map(r=>r.slice(1)));
assert.equal(hoursOnly.inferred.layout,'hours');assert.equal(hoursOnly.sensors.length,10);
const dateOnly=C.parseMatrix(withoutHeaders.slice(0,149).map(r=>[r[0],...r.slice(2)]));
assert.equal(dateOnly.inferred.layout,'date');assert.equal(dateOnly.sensors.length,10);
const single=C.parseMatrix([withoutHeaders[0]]);
assert.equal(single.rows.length,1);assert.equal(single.inferred.layout,'date-hours');
const onlyTwo=C.parseMatrix([['35.26','36.01'],['36.4','38.1']]);
assert.equal(onlyTwo.sensors.length,2);assert.deepEqual(C.calculate(onlyTwo,[{a:2,b:1}]).rows,[['',1,0.75],['',2,1.7]]);
// Both identifying columns are always present, including copies and exports.
const timed=C.calculate(onlyTwo,[{a:2,b:1}],'signed',{start:'2026-09-01T23:45',interval:30,firstHour:4});
assert.deepEqual(timed.headers,['Date & Time','Hours(1/2 Hrs)','T2-T1']);
assert.deepEqual(timed.rows,[['01/09/2026 23:45',4,0.75],['02/09/2026 00:15',5,1.7]]);
assert.deepEqual(C.readTSV(C.toTSV(timed))[1],['01/09/2026 23:45','4','0.75']);
assert.equal(C.calculate(onlyTwo,[{a:2,b:1}],'signed',{interval:60}).rows[1][1],3);
assert.throws(()=>C.calculate(onlyTwo,[],'signed',{start:'2026-02-30T12:00'}),/valid first/);
assert.throws(()=>C.calculate(onlyTwo,[],'signed',{interval:0}),/interval/);
assert.throws(()=>C.calculate(onlyTwo,[],'signed',{firstHour:NaN}),/starting Hours/);
const originalTiming=C.calculate(clipboardSource,pairs,'signed',{start:'2020-01-01T00:00',interval:60,firstHour:500});
originalTiming.rows.forEach((row,i)=>{
  assert.equal(row[0],sheet[`M${i+9}`].w);
  assert.equal(String(row[1]),sheet[`N${i+9}`].w);
});
assert(C.calculate(hoursOnly,pairs).rows.every((r,i)=>r[0]===''&&r[1]===hoursOnly.rows[i][0]));
assert(C.calculate(dateOnly,pairs).rows.every((r,i)=>r[0]===dateOnly.rows[i][0]&&r[1]===i+1));
const blankMetadata=C.parseMatrix([['Date & Time','Hours','Temp-1','Temp-2'],['','',35,36],['9/1/26 11:30',8,36,37]]);
assert.deepEqual(C.calculate(blankMetadata,[{a:2,b:1}]).rows[0],['','',1]);
const ambiguous=[[1,30,40],[2,31,41]];
assert.equal(C.parseMatrix(ambiguous).inferred.layout,'hours');
assert.equal(C.parseMatrix(ambiguous,{layout:'temperatures'}).sensors.length,3);
assert.equal(C.parseMatrix(withoutHeaders.slice(0,149),{ambient:false}).sensors[9].ambient,false);
assert.equal(C.parseMatrix([['9/1/26 11:00',145,35,36],['9/1/26 11:30',146,36,37]]).inferred.layout,'date-hours');
const missingNoHeaders=C.parseMatrix([['9/1/26 11:00',1,'',36],['9/1/26 11:30',2,35,36]]);
assert.equal(C.calculate(missingNoHeaders,[{a:2,b:1}]).missing,1);
assert.throws(()=>C.parseMatrix([[35],[36]]),/at least two/);
const adjacent=C.makePairs(source.sensors,'adjacent');
assert.deepEqual(adjacent,[{a:2,b:1},{a:4,b:3},{a:6,b:5},{a:8,b:7}]);
assert(!adjacent.some(p=>p.a===10||p.b===10),'Ambient excluded from presets');
assert.deepEqual(C.calculate(source,pairs,'absolute').rows[0].slice(2),[0.75,0.10,0.93,0.38,0.85,0.95]);
const dirty=C.parseMatrix([['Date & Time','Hours','Temp-1','Temp-2'],['now','0','0','2'],['later','1','','8'],['last','2','#N/A','9'],['negative','3','4','-1']]);
const dr=C.calculate(dirty,[{a:2,b:1}]);
assert.deepEqual(dr.rows.map(r=>r[2]),[2,null,null,-5]);assert.equal(dr.missing,2);
const missingRow=C.parseMatrix([['Date & Time','Temp-1','Temp-2'],['9/1/26 11:00','','']]);
assert.equal(missingRow.rows.length,1);assert.equal(C.calculate(missingRow,[{a:2,b:1}]).missing,1);
assert.deepEqual(C.readTSV('"Date\nTime"\tTemp-1\tTemp-2\r\nx\t"1"\t2\r\n'),[['Date\nTime','Temp-1','Temp-2'],['x','1','2']]);
assert.equal(C.readTSV(Array.from({length:24},(_,i)=>i).join('\t'))[0].length,21);
assert.throws(()=>C.parseMatrix([['Temp-1','Temp-1'],[1,2]]),/twice/);
assert.throws(()=>C.parseMatrix([['foo','bar'],[1,2]]),/headers/);
const filtered=D.selectRows(table.rows,{column:'2',contains:'35.3'});
assert(filtered.length>0);assert(filtered.every(r=>r.cells[2].text.includes('35.3')));
const sorted=D.selectRows(table.rows,{sort:2,direction:-1});
const nums=sorted.map(r=>r.cells[2].value).filter(v=>typeof v==='number');
assert(nums.every((n,i)=>i===0||nums[i-1]>=n));
const out=X.utils.book_new();X.utils.book_append_sheet(out,D.exportSheet(table.headers,filtered,X),'Filtered');
const reloaded=X.read(X.write(out,{type:'buffer',bookType:'xlsx'}),{type:'buffer'});
assert.equal(X.utils.decode_range(reloaded.Sheets.Filtered['!ref']).e.c,20);
assert.equal(X.utils.sheet_to_json(reloaded.Sheets.Filtered,{header:1}).length,filtered.length+1);
assert.equal(C.readTSV(C.toTSV(result)).length,result.rows.length+1);
console.log(`Verified ${result.rows.length} temperature readings, ${compared} saved differences, headerless date/hours/temperature layouts, single rows, mapping overrides, paste parsing, adjacent and absolute pairs, missing values, A–U exclusion, search, sort and export round trip.`);
